[versions]
agp = "8.13.2"
core = "1.7.0"
kermit = "2.0.8"
kotlin = "2.2.20"
android-minSdk = "24"
android-compileSdk = "36"
vanniktechMavenPublish = "0.36.0"
libaryVersion = "0.0.3"
kotlinSerialization = "1.9.0" # https://github.com/Kotlin/kotlinx.serialization/releases
kotlinCoroutines = "1.10.2" # https://github.com/Kotlin/kotlinx.coroutines/releases
ktor = "3.2.3" # https://github.com/ktorio/ktor/releases
slf4jAndroid="1.7.36"
slf4jJvm="2.0.17"
kotlinx-browser="0.3"
sqlDelight = "2.2.1"
okio = "3.16.4"
oshiCore = "6.9.3"
robolectric = "4.16.1"
mockitoCore = "5.21.0"
kotlinxDatetime = "0.7.1"
coroutines = "1.10.2"
kotlinxSerialization = "1.10.0"

[libraries]
kermit = { module = "co.touchlab:kermit", version.ref = "kermit" }
kermit-test = { module = "co.touchlab:kermit-test", version.ref = "kermit" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
core = { module = "androidx.test:core", version.ref = "core" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinxDatetime" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerialization" }
kotlinx-serialization-cbor = { module = "org.jetbrains.kotlinx:kotlinx-serialization-cbor", version.ref = "kotlinxSerialization" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
android-driver = { module = "app.cash.sqldelight:android-driver", version.ref = "sqlDelight" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockitoCore" }
native-driver = { module = "app.cash.sqldelight:native-driver", version.ref = "sqlDelight" }
okio = { module = "com.squareup.okio:okio", version.ref = "okio" }
oshi-core = { module = "com.github.oshi:oshi-core", version.ref = "oshiCore" }
robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectric" }
sqlite-driver = { module = "app.cash.sqldelight:sqlite-driver", version.ref = "sqlDelight" }

[plugins]
android-kotlin-multiplatform-library = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
vanniktech-mavenPublish = { id = "com.vanniktech.maven.publish", version.ref = "vanniktechMavenPublish" }
sqlDelight = { id = "app.cash.sqldelight", version.ref = "sqlDelight" }
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }